global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "sequencer"
    static_configs:
      - targets: ["sequencer:6060"]
    metrics_path: /metrics

  - job_name: "validator"
    static_configs:
      - targets: ["validator:6061"]
    metrics_path: /metrics
